//
// Created by fakhri on 12/15/19.
//

#ifndef LXQT_PANEL_SETTINGS_H
#define LXQT_PANEL_SETTINGS_H

#define ACCOUNT_STATUS_ICON_SIZE 20
#define MAIN_MENU_SIZE_W  250
#define ACCOUNT_ICON_SIZE 15
#define MESSAGE_ICON_SIZE 15
#define UPDATE_ICON_SIZE 15
#define MAX_ACCOUNT_SIZE 20


#endif //LXQT_PANEL_SETTINGS_H
