//
// Created by fakhri on 12/15/19.
//

#ifndef LXQT_PANEL_SETTINGS_H
#define LXQT_PANEL_SETTINGS_H

#define ACCOUNT_STATUS_ICON_SIZE 20
#define MAIN_MENU_SIZE_W  400
#define ACCOUNT_ICON_SIZE 32
#define MESSAGE_ICON_SIZE 32

#endif //LXQT_PANEL_SETTINGS_H
